name: "It's broken"
description: Report or request removal of incorrectly included domains
title: "[BROKEN] "
labels: ["broken", "needs-review"]
body:
  - type: dropdown
    id: issue-type
    attributes:
      label: What type of issue is this?
      description: Is this a missing site/domain or should something be removed?
      options:
        - Incorrectly included (should be whitelisted)
        - Other
    validations:
      required: true

  - type: input
    id: domain
    attributes:
      label: Domain
      description: The domain that needs to be whitelisted
      placeholder: example.com
    validations:
      required: true

  - type: checkboxes
    id: verification
    attributes:
      label: Verification
      description: Please confirm you've checked these before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: This is related to Russian internet restrictions
          required: true
        - label: I understand this is a manual review process and may take time
          required: true